# Generated by Django 3.0.5 on 2020-09-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200926_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='bio',
        ),
    ]
